/**
 * On-demand loading of the non-Latin script fonts (self-hosted Noto Sans,
 * src/styles/script-fonts/, generated by scripts/generate-font-css.mjs).
 * Each script's CSS is a separate chunk that's only fetched the first time
 * a project actually renders that script — an English-only project never
 * loads any of it — and even then the browser only downloads the
 * unicode-range slices for the characters drawn.
 *
 * Importing this module registers the loader with the engine
 * (setScriptFontCssLoader), so engine exports can make sure a script font
 * is present before drawing.
 */
import { setScriptFontCssLoader } from '@/engine/fonts';
import type { ScriptKey } from '@/engine/locales';

const CSS: Record<Exclude<ScriptKey, 'latin'>, () => Promise<unknown>> = {
  cyrillic: () => import('@/styles/script-fonts/cyrillic.css'),
  jp: () => import('@/styles/script-fonts/jp.css'),
  kr: () => import('@/styles/script-fonts/kr.css'),
  sc: () => import('@/styles/script-fonts/sc.css'),
  tc: () => import('@/styles/script-fonts/tc.css'),
  arabic: () => import('@/styles/script-fonts/arabic.css'),
  hebrew: () => import('@/styles/script-fonts/hebrew.css'),
  devanagari: () => import('@/styles/script-fonts/devanagari.css'),
};

const loaded = new Map<ScriptKey, Promise<void>>();

export function loadScriptFontCss(script: ScriptKey): Promise<void> {
  if (script === 'latin') return Promise.resolve();
  let p = loaded.get(script);
  if (!p) loaded.set(script, (p = CSS[script]().then(() => undefined)));
  return p;
}

setScriptFontCssLoader(loadScriptFontCss);
