/**
 * One-time (or re-run-anytime) seed script for the curated music library —
 * procedurally generates the placeholder tracks in
 * src/engine/audio/proceduralMusic.ts, encodes them to WAV, and uploads
 * them to the public R2 bucket (under music-library/) + the `music_tracks` table
 * (see supabase/migrations/0006_music_library.sql) using the service-role
 * key. These are clearly-labeled placeholder tracks (see that file's doc
 * comment) proving the library pipeline end to end, not an attempt at
 * production music — swap in real licensed tracks the same way whenever
 * you have them.
 *
 * Run with:
 *   node --env-file=.env.local scripts/seed-music-library.ts
 *
 * Requires NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY and the R2_*
 * variables in .env.local (the same ones the app's server uses).
 */
import { createClient } from '@supabase/supabase-js';

import { r2FromEnv } from './lib/r2.mjs';
import { MUSIC_TRACK_DEFS, generateProceduralTrack } from '../src/engine/audio/proceduralMusic.ts';
import { encodeWavMono } from '../src/engine/audio/wav.ts';

const SAMPLE_RATE = 44100;

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY. Run with: node --env-file=.env.local scripts/seed-music-library.ts');
    process.exit(1);
  }
  const supabase = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });
  const r2 = r2FromEnv();

  for (const def of MUSIC_TRACK_DEFS) {
    const samples = generateProceduralTrack(def, SAMPLE_RATE);
    const wav = encodeWavMono(samples, SAMPLE_RATE);
    const storagePath = `${def.id}.wav`;
    const durationSeconds = samples.length / SAMPLE_RATE;

    console.log(`Uploading ${storagePath} (${durationSeconds.toFixed(2)}s, ${def.bpm} BPM)…`);
    await r2.put(r2.bucketName('public'), `music-library/${storagePath}`, wav, 'audio/wav', 'public, max-age=31536000');

    const { error: dbError } = await supabase.from('music_tracks').upsert({
      id: def.id,
      name: def.name,
      storage_path: storagePath,
      bpm: def.bpm,
      duration_seconds: durationSeconds,
      category: def.category,
      // Procedurally generated by generateProceduralTrack() above — ours,
      // not third-party audio (see 0011_music_license.sql).
      license: 'original',
      author: 'Nimina',
    });
    if (dbError) throw dbError;
    console.log(`  done: ${def.name}`);
  }

  console.log(`Seeded ${MUSIC_TRACK_DEFS.length} tracks.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
