/**
 * Seeds the placeholder tracks of the music library — procedurally generated
 * from src/engine/audio/proceduralMusic.ts, so genuinely ours — as 128 kbps
 * MP3s with waveform peaks, the same format /admin/music produces for real
 * tracks. Re-run any time (upserts by id). Real, licensed music is added
 * from /admin/music, not here.
 *
 * Earlier runs stored WAVs (`<id>.wav`); those files are left in place so
 * projects that picked one keep playing it.
 *
 * Run with:
 *   node --env-file=.env.local scripts/seed-music-library.ts
 *
 * Requires NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY and the R2_*
 * variables in .env.local (migration 0022 applied).
 */
import { Mp3Encoder } from '@breezystack/lamejs';
import { createClient } from '@supabase/supabase-js';

import { r2FromEnv } from './lib/r2.mjs';
import { MUSIC_TRACK_DEFS, generateProceduralTrack } from '../src/engine/audio/proceduralMusic.ts';

const SAMPLE_RATE = 44100;
const KBPS = 128;

function encodeMp3(samples: Float32Array): Uint8Array {
  const enc = new Mp3Encoder(1, SAMPLE_RATE, KBPS);
  const pcm = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i++) pcm[i] = Math.max(-32768, Math.min(32767, samples[i] * 32767));
  const parts: Uint8Array[] = [];
  for (let i = 0; i < pcm.length; i += 1152) {
    const out = enc.encodeBuffer(pcm.subarray(i, i + 1152));
    if (out.length) parts.push(new Uint8Array(out));
  }
  parts.push(new Uint8Array(enc.flush()));
  const bytes = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let o = 0;
  for (const p of parts) {
    bytes.set(p, o);
    o += p.length;
  }
  return bytes;
}

function peaks(samples: Float32Array, buckets = 160): number[] {
  const size = Math.floor(samples.length / buckets);
  const raw = Array.from({ length: buckets }, (_, b) => {
    let m = 0;
    for (let i = b * size; i < (b + 1) * size; i++) m = Math.max(m, Math.abs(samples[i]));
    return m;
  });
  const top = Math.max(...raw, 1e-6);
  return raw.map((v) => Math.round((v / top) * 1000) / 1000);
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY. Run with: node --env-file=.env.local scripts/seed-music-library.ts');
    process.exit(1);
  }
  const supabase = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });
  const r2 = r2FromEnv();

  for (const [i, def] of MUSIC_TRACK_DEFS.entries()) {
    const samples = generateProceduralTrack(def, SAMPLE_RATE);
    const mp3 = encodeMp3(samples);
    const storagePath = `${def.id}.mp3`;
    const durationSeconds = samples.length / SAMPLE_RATE;

    console.log(`Uploading ${storagePath} (${durationSeconds.toFixed(2)}s, ${(mp3.length / 1024).toFixed(0)} KB, ${def.bpm} BPM)…`);
    await r2.put(r2.bucketName('public'), `music-library/${storagePath}`, mp3, 'audio/mpeg', 'public, max-age=31536000, immutable');

    const { error: dbError } = await supabase.from('music_tracks').upsert({
      id: def.id,
      name: def.name,
      storage_path: storagePath,
      bpm: def.bpm,
      duration_seconds: durationSeconds,
      category: def.category,
      mood: def.category,
      genre: 'Electronic',
      artist: 'Nimina',
      author: 'Nimina',
      // Generated by generateProceduralTrack() above — ours, not third-party audio.
      license: 'original',
      licence_source: 'Original — made by Nimina',
      licence_notes: 'Procedurally generated placeholder (src/engine/audio/proceduralMusic.ts). We own it outright; no third-party rights.',
      peaks: peaks(samples),
      bytes: mp3.length,
      bitrate_kbps: KBPS,
      sort_order: i,
    });
    if (dbError) throw dbError;
    console.log(`  done: ${def.name}`);
  }

  console.log(`Seeded ${MUSIC_TRACK_DEFS.length} tracks.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
