-- Every built-in asset we ship must be traceable to either something we
-- made ourselves or a commercial license we hold (Prompt 7). The curated
-- music library (0006_music_library.sql) is procedurally generated by
-- scripts/seed-music-library.ts from src/engine/audio/proceduralMusic.ts —
-- genuinely ours, not third-party audio — so 'original' is accurate for
-- every row seeded so far. Mirrors src/engine2/assetLicense.ts's
-- AssetLicense shape so the same three kinds mean the same thing everywhere.

alter table public.music_tracks
  add column if not exists license text not null default 'original'
    check (license in ('original', 'cc0', 'licensed')),
  add column if not exists license_note text,
  add column if not exists author text;

comment on column public.music_tracks.license is
  'original: we made it. cc0: public-domain third-party work. licensed: a specific commercial license we hold — license_note must say what/where.';
